import { robotoFlex } from "@/utils/fonts/globalFont";
import "./globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Music GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={robotoFlex.className} lang="en">
      <body className="flex flex-col md:flex-row min-h-screen">
        <header className="flex md:hidden sticky top-0 z-40">
          <Header />
        </header>

        <div className="w-80 hidden md:flex h-screen">
          <Sidebar />
        </div>
        <main className="w-full h-full z-30 bg-yellow-100">
          <div className="flex w-full max-w-screen-xl mx-auto grow bg-green-200">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}

// CSR("use client") SSG ISR SSR(default)
// hybrid
