import { robotoFlex } from "@/utils/fonts/globalFont";
import "./globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Music GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={robotoFlex.className} lang="en">
      <body className="flex flex-col md:flex-row overflow-x-scroll">
        <header className="flex md:hidden sticky top-0 z-40">
          <Header />
        </header>

        {/* Sidebar: greater than md */}
        <div className="hidden md:flex">
          <Sidebar />
        </div>

        <main className="flex-[1_1_0] overflow-auto">
          <div className="max-w-screen-xl mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}

// CSR("use client") SSG ISR SSR(default)
// hybrid
